language: python
python:
  - "2.7"
install:
  - pip install --upgrade google-api-python-client
  - pip install pylint
script:
  - find . -regex ".*\.py" -print0 | xargs -0 pylint --errors-only --disable=print-statement